Controllers/ActionController.cs
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using ActivityCenter.Models;

namespace ActivityCenter.Controllers
{
    public class ActionController : Controller
    {
        private MyContext _context;
        public ActionController(MyContext context)
        {
            _context = context;
        }

        [HttpGet("delete/{ActivityId}")]
        public RedirectToActionResult Delete(int ActivityId)
        {
            Activity toDelete = _context.Activities.FirstOrDefault(w => w.ActivityId == ActivityId);
            _context.Remove(toDelete);
            _context.SaveChanges();
            return RedirectToAction("Dashboard", "Home");
        }

        [HttpGet("join/{ActivityId}")]
        public RedirectToActionResult Join(int ActivityId)
        {
            int UserId = (int)HttpContext.Session.GetInt32("UserId");
            UserActivity ActivityList = _context.UserActivities.Include(b => b.Participant).FirstOrDefault(a => a.Participant.UserId == UserId && a.Activity.ActivityId == ActivityId);
            if (ActivityList == null)
            {
                UserActivity NewActivity = new UserActivity { };
                User ExistingUser = _context.Users.FirstOrDefault(u => u.UserId == UserId);
                Activity ExistingActivity = _context.Activities.FirstOrDefault(w => w.ActivityId == ActivityId);
                NewActivity.Participant = ExistingUser;
                NewActivity.Activity = ExistingActivity;
                _context.Add(NewActivity);
            }
            else
            {
                _context.Remove(ActivityList);
            }
            _context.SaveChanges();
            return RedirectToAction("Dashboard", "Home");
        }

        [HttpPost("new")]
        public IActionResult CreateActivity(Activity fromForm)
        {
            Activity Activity = new Activity { };
            if (ModelState.IsValid)
            {
                int UserId = (int)HttpContext.Session.GetInt32("UserId");

                User ExistingUser = _context.Users.FirstOrDefault(u => u.UserId == UserId);

                fromForm.Creator = ExistingUser;

                _context.Add(fromForm);
                _context.SaveChanges();

                UserActivity NewActivity = new UserActivity { };

                Activity ExistingActivity = _context.Activities.FirstOrDefault(w => w.ActivityId == fromForm.ActivityId);

                NewActivity.Participant = ExistingUser;

                NewActivity.Activity = ExistingActivity;
                _context.Add(NewActivity);
                _context.SaveChanges();
                int ActivityId = ExistingActivity.ActivityId;
                return RedirectToAction("Activity", "Home", new { ActivityId = ActivityId});
            }
            return View("NewActivity", Activity);
        }
    }
}

Controllers/RegLoginController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using ActivityCenter.Models;

namespace ActivityCenter.Controllers
{
    public class RegLoginController : Controller
    {
        private MyContext _context;
        public RegLoginController(MyContext context)
        {
            _context = context;
        }

        [HttpPost("register")]
        public IActionResult RegisterUser(User fromForm)
        {
            RegLogWrapper FormWrapper = new RegLogWrapper { };
            if (ModelState.IsValid)
            {
                if (_context.Users.Any(u => u.Email == fromForm.Email)) //u.____/fromForm.____ is based on input field
                {
                    ModelState.AddModelError("RegisterEmail", "Email taken");
                    return View("../Home/Index", FormWrapper);
                }
                else
                {
                    PasswordHasher<User> Hasher = new PasswordHasher<User>();
                    fromForm.Password = Hasher.HashPassword(fromForm, fromForm.Password);
                    _context.Add(fromForm);
                    _context.SaveChanges();
                    HttpContext.Session.SetInt32("UserId", fromForm.UserId);
                    return RedirectToAction("Dashboard", "Home");
                }
            }
            return View("../Home/Index", FormWrapper);
        }

        [HttpPost("login")]
        public IActionResult LoginUser(LoginUser fromForm)
        {
            RegLogWrapper FormWrapper = new RegLogWrapper { };
            if (ModelState.IsValid)
            {
                User ExistingUser = _context.Users.FirstOrDefault(u => u.Email == fromForm.UserEmail);
                if (ExistingUser == null)
                {
                    ModelState.AddModelError("LoginEmail", "Invalid email");
                    return View("../Home/Index", FormWrapper);
                }
                PasswordHasher<LoginUser> Hasher = new PasswordHasher<LoginUser>();
                PasswordVerificationResult result = Hasher.VerifyHashedPassword(fromForm, ExistingUser.Password, fromForm.UserPassword);
                if (result == 0)
                {
                    ModelState.AddModelError("LoginEmail", "Password error");
                    return View("../Home/Index", FormWrapper);
                }
                HttpContext.Session.SetInt32("UserId", ExistingUser.UserId);
                return RedirectToAction("Dashboard", "Home");
            }
            return View("../Home/Index", FormWrapper);
        }

        [HttpGet("logout")]
        public RedirectToActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

Views/Shared/ActivityPartial.cshtml
@using ActivityCenter.Models
@model Activity

<span asp-validation-for="Title"></span>
<label asp-for="Title"></label>
<input asp-for="Title">
<span asp-validation-for="Date"></span>
<label asp-for="Date"></label>
<input asp-for="Date">
<span asp-validation-for="Time"></span>
<label asp-for="Time"></label>
<input asp-for="Time">
<span asp-validation-for="Duration"></span>
<label asp-for="Duration"></label>
<input asp-for="Duration">
<select asp-for="DurationSpan">
    <option value="minutes">Minutes</option>
    <option value="hours">Hours</option>
    <option value="days">Days</option>
</select>
<span asp-validation-for="Description"></span>
<label asp-for="Description"></label>
<input asp-for="Description">

Views/Shared/NewActivity.cshtml
@using ActivityCenter.Models
@model Activity

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="/css/style_form.css">

</head>
<body>
    <div id="container">

    <header>
        <h1>Dojo Activity Center</h1>
        <p><a asp-action="Dashboard" asp-controller="Home">Home</a></p>
        <p><a asp-action="Logout" asp-controller="RegLogin">Logout</a></p>
    </header>

    <form asp-action="CreateActivity" asp-controller="Action">
        <partial name="ActivityPartial" model="Model" />
        <button>Create Activity</button>
    </form>

</div>
</body>
</html>